sudo: required
services:
    - docker

before_install:
    - docker build -t raspopovsergey/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true raspopovsergey/react-test npm run test

after_success:
    - docker build -t raspopovsergey/multi-client ./client
    - docker build -t raspopovsergey/multi-nginx ./nginx
    - docker build -t raspopovsergey/multi-server ./server
    - docker build -t raspopovsergey/multi-worker ./worker
    #login into docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #push images to docker hub
    - docker push raspopovsergey/multi-client
    - docker push raspopovsergey/multi-nginx
    - docker push raspopovsergey/multi-server
    - docker push raspopovsergey/multi-worker

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-west-2-778627590623"
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY